### ISSUE TITLE
Rscript: command not found error after el Capitan update

### ISSUE THREAD

**Issue by jvcasillas** [andrewheiss/SublimeKnitr#32]
After updating Mac OS X to El Capitan, I can no longer knit .Rmd files in sublimetext. Specifically, I get the following error when trying to build:

```
/bin/sh: Rscript: command not found
[Finished in 0.1s with exit code 127]
[cmd: ['Rscript -e "library(knitr); knit(\'/Users/username/Desktop/test.Rmd\', output=\'/Users/username/Desktop/test.md\')"']]
[dir: /Users/username/Desktop]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
```

This looks like a simple fix (just changing the path in sublimetext); however, I am not sure how this is done. I can knit files with no issues form RStudio. Any ideas?

**Comment by andrewheiss** [comment]
This isn't necessarily an issue with Sublime Text (or SublimeKnitr), but with a change El Capitan made with permissions. Apparently it doesn't allow programs to install to `/usr` anymore, so Rscript is off limits systemwide (you can verify this by opening Terminal and trying to run Rscript there or typing `which Rscript`). 

[Someone reported it as a bug on the R project](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16469), and it seems to have been resolved by putting everything in `/usr/local/bin`, but you might have to reinstall R to make it work. (I haven't tried this yet—I also no longer have access to `Rscript` with El Capitan). 

Knitting works from RStudio because it accesses R directly instead of using RScript through the terminal.

**Comment by andrewheiss** [comment]
Yep. Reinstall R and it should work right:

    ~ : which Rscript
    /usr/local/bin/Rscript

**Comment by jvcasill** [comment]
I reinstalled R and I now have Rscript in the same path you describe; however, I still get the same error. When I do a system check using LaTeXing it now finds Rscript. How do I tell the build system to use the new path? Do I need to update this somewhere else?

**Comment by andrewheiss** [comment]
Make sure `/usr/local/bin` is in your `$PATH` variable in `~/.bash_profile`?

**Comment by jvcasill** [comment]
I'm still having trouble getting this to work. Is it working for you? Did you put ```/usr/local/bin``` in your ```$PATH``` variable the same way you suggest (i.e. in ```~/.bash_profile```)?

**Comment by jvcasill** [comment]
After double checking, ```/usr/local/bin``` is already in my path. I'm not really sure what to try now.

**Comment by andrewheiss** [comment]
It turns out that Sublime Text does *not* read anything from `~/.bash_profile`

That said, I can't reproduce this error using El Capitan—ST 3 is picking up the new location for `Rscript`

**Comment by ashutosh-gupta** [comment]
I am having a similar issue, that is partly resolved based on comments above. 
Initially, Rscript was giving an error. 
 
After reinstalling R, the command Rscript command works. 
However, the same Rscript command doesn't work for my cron jobs.

**Comment by zhouyisu** [comment]
@andrewheiss , I am running into this same issue. Would you show how I could reinstall R to `/usr/local/bin`?

**Comment by andrewheiss** [comment]
Downloading R from r-project.org and reinstalling it should fix it…

**Comment by kofm** [comment]
It doesn't fix it.
Same error for me:

/bin/sh: Rscript: command not found
[Finished in 0.1s with exit code 127]
[cmd: ['Rscript -e "library(knitr); knit(\'/Users/user/Desktop/a\', output=file.path(\'/Users/user/Desktop\', \'a.md\'))"']]
[dir: /Users/user/Desktop]
[path: /usr/bin:/bin:/usr/sbin:/sbin]

**Comment by andrewheiss** [comment]
Can you build using the "R Markdown" build command in this package: https://github.com/randy3k/R-Box ?

The build file there and in this package are almost identical, so it'd be interesting to see if you're getting the same errors there.

**Comment by kofm** [comment]
I managed to resolve the issue installing the [SublimeFixMacPath package](https://github.com/int3h/SublimeFixMacPath). Now all works flawlessy.
As you said before:
> It turns out that Sublime Text does not read anything from ~/.bash_profile

Thanks for support

**Comment by liangyy** [comment]
I found Rscript at `/Library/Frameworks/R.framework/Resources/bin/`
